package vista;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelo.CBarraProgreso;
import modelo.CCredencial;
import modelo.CDibujaFoto;
import modelo.CExpediente;
import modelo.CTrabajador;

/**
 *
 * @author Angel
 */

public class jd_buscarTrabajador extends javax.swing.JDialog {

    /**
     * Creates new form jd_buscarTrabajador
     */
    CTrabajador trabajador;
    CExpediente exp;
    CCredencial cred;
    DefaultTableModel modelo;
    CDibujaFoto foto;
    CBarraProgreso barritaProgreso;
    jd_progreso prog;
    jd_telefonos telefonos = null;
    private JFileChooser jfc;
    
    int i;
    
    public jd_buscarTrabajador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        trabajador = new CTrabajador();
        cred = new CCredencial();
        foto = new CDibujaFoto(jPanel5);
        jPanel5.add(foto);
        setLocationRelativeTo(parent);
        exp = new CExpediente();
        prog = new jd_progreso(parent, true);
        jfc = new JFileChooser();
        jfc.setFileFilter(new FileNameExtensionFilter("Archivo Imagen", "jpg" , "jpeg", "png"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jmi_abririnfo = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jmi_abrir = new javax.swing.JMenuItem();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jmiActualizarTelefono = new javax.swing.JMenuItem();
        jmi_agregarTelefono = new javax.swing.JMenuItem();
        jmiBorrarTelefono = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jl_nombre = new javax.swing.JLabel();
        jl_nombreMostrar = new javax.swing.JLabel();
        jl_domicilio = new javax.swing.JLabel();
        jl_domicilioMostrar = new javax.swing.JLabel();
        jl_curp = new javax.swing.JLabel();
        jl_curpMostrar = new javax.swing.JLabel();
        jl_claveElector = new javax.swing.JLabel();
        jl_claveElectorMostrar = new javax.swing.JLabel();
        jl_rfc = new javax.swing.JLabel();
        jl_rfcMostrar = new javax.swing.JLabel();
        jl_estudios = new javax.swing.JLabel();
        jl_estudiosMostrar = new javax.swing.JLabel();
        jl_especialidad = new javax.swing.JLabel();
        jl_especialidadMostrar = new javax.swing.JLabel();
        jl_convenioMedico = new javax.swing.JLabel();
        jl_convenioMedicoMostrar = new javax.swing.JLabel();
        jl_tipoSangre = new javax.swing.JLabel();
        jl_tipoSangreMostrar = new javax.swing.JLabel();
        jl_fechaNacimiento = new javax.swing.JLabel();
        jl_fechaNacimientoMostrar = new javax.swing.JLabel();
        jl_recomendado = new javax.swing.JLabel();
        jl_recomendadoMostrar = new javax.swing.JLabel();
        jl_apodo = new javax.swing.JLabel();
        jl_apodoMostrar = new javax.swing.JLabel();
        jl_estadoCivil = new javax.swing.JLabel();
        jl_estadocivilMostrar = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jb_actualizarFoto = new javax.swing.JButton();
        jl_concuvina = new javax.swing.JLabel();
        jl_concuvinaMostrar = new javax.swing.JLabel();
        jl_domicilio2 = new javax.swing.JLabel();
        jl_domicilio3 = new javax.swing.JLabel();
        jl_hijos_mostrar = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_contratos = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_credenciales = new javax.swing.JTable();

        jmi_abririnfo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jmi_abririnfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nueva_ventana.png"))); // NOI18N
        jmi_abririnfo.setText("Ver Informacion");
        jmi_abririnfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_abririnfoActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jmi_abririnfo);

        jmi_abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nueva_ventana.png"))); // NOI18N
        jmi_abrir.setText("Abrir ...");
        jmi_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_abrirActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jmi_abrir);

        jmiActualizarTelefono.setText("Actualizar Telefono");
        jmiActualizarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiActualizarTelefonoActionPerformed(evt);
            }
        });
        jPopupMenu3.add(jmiActualizarTelefono);

        jmi_agregarTelefono.setText("Agregar Telefono");
        jmi_agregarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarTelefonoActionPerformed(evt);
            }
        });
        jPopupMenu3.add(jmi_agregarTelefono);

        jmiBorrarTelefono.setText("Eliminar Telefono");
        jmiBorrarTelefono.setToolTipText("");
        jmiBorrarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBorrarTelefonoActionPerformed(evt);
            }
        });
        jPopupMenu3.add(jmiBorrarTelefono);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda Trabajador");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Busqueda:");

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 153, 0));
        jTextField1.setToolTipText("Busca un trabajador por su numero de ficha o nombre");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 102, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Ficha", "Nombre", "Apellido Paterno", "Apellido Materno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1127, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Busqueda", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jl_nombre.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_nombre.setText("Nombre:");

        jl_nombreMostrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_nombreMostrar.setForeground(new java.awt.Color(0, 102, 0));
        jl_nombreMostrar.setText("     ");

        jl_domicilio.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_domicilio.setText("Domicilio:");

        jl_domicilioMostrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_domicilioMostrar.setForeground(new java.awt.Color(0, 102, 0));
        jl_domicilioMostrar.setText("  ");

        jl_curp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_curp.setText("Curp:");

        jl_curpMostrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_curpMostrar.setForeground(new java.awt.Color(0, 102, 0));
        jl_curpMostrar.setText("   ");

        jl_claveElector.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_claveElector.setText("Clave Elector:");

        jl_claveElectorMostrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_claveElectorMostrar.setForeground(new java.awt.Color(0, 102, 0));
        jl_claveElectorMostrar.setText("   ");

        jl_rfc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_rfc.setText("Rfc:");

        jl_rfcMostrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_rfcMostrar.setForeground(new java.awt.Color(0, 102, 0));
        jl_rfcMostrar.setText("  ");

        jl_estudios.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_estudios.setText("Nivel De Estudios:");

        jl_estudiosMostrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_estudiosMostrar.setForeground(new java.awt.Color(0, 102, 0));
        jl_estudiosMostrar.setText("   ");

        jl_especialidad.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_especialidad.setText("Especialidad:");

        jl_especialidadMostrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_especialidadMostrar.setForeground(new java.awt.Color(0, 102, 0));
        jl_especialidadMostrar.setText("  ");

        jl_convenioMedico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_convenioMedico.setText("Convenio Medico:");

        jl_convenioMedicoMostrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_convenioMedicoMostrar.setForeground(new java.awt.Color(0, 102, 0));
        jl_convenioMedicoMostrar.setText("   ");

        jl_tipoSangre.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_tipoSangre.setText("Tipo Sangre:");

        jl_tipoSangreMostrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_tipoSangreMostrar.setForeground(new java.awt.Color(0, 102, 0));
        jl_tipoSangreMostrar.setText("  ");

        jl_fechaNacimiento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_fechaNacimiento.setText("Fecha Nacimiento:");

        jl_fechaNacimientoMostrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_fechaNacimientoMostrar.setForeground(new java.awt.Color(0, 102, 0));
        jl_fechaNacimientoMostrar.setText("   ");

        jl_recomendado.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_recomendado.setText("Recomendado:");

        jl_recomendadoMostrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_recomendadoMostrar.setForeground(new java.awt.Color(0, 102, 0));
        jl_recomendadoMostrar.setText("   ");

        jl_apodo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_apodo.setText("Apodo:");

        jl_apodoMostrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_apodoMostrar.setForeground(new java.awt.Color(0, 102, 0));
        jl_apodoMostrar.setText("   ");

        jl_estadoCivil.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_estadoCivil.setText("Estado Civil:");

        jl_estadocivilMostrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_estadocivilMostrar.setForeground(new java.awt.Color(0, 102, 0));
        jl_estadocivilMostrar.setText("   ");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel28.setText("Hijos:");

        jTable2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Fecha Nacimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel29.setText("Telefonos:");

        jTable3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Telefono", "Tipo "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setComponentPopupMenu(jPopupMenu3);
        jScrollPane3.setViewportView(jTable3);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jb_actualizarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/recycle-29933_960_720.png"))); // NOI18N
        jb_actualizarFoto.setToolTipText("Actualiza Foto del Trabajador");
        jb_actualizarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_actualizarFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_actualizarFoto)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addComponent(jb_actualizarFoto)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jl_concuvina.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_concuvina.setText("Concuvina(o):");

        jl_concuvinaMostrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_concuvinaMostrar.setForeground(new java.awt.Color(0, 102, 0));
        jl_concuvinaMostrar.setText("   ");

        jl_domicilio2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_domicilio2.setForeground(new java.awt.Color(0, 102, 0));
        jl_domicilio2.setText("   ");

        jl_domicilio3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_domicilio3.setForeground(new java.awt.Color(0, 102, 0));
        jl_domicilio3.setText("   ");

        jl_hijos_mostrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_hijos_mostrar.setForeground(new java.awt.Color(0, 102, 0));
        jl_hijos_mostrar.setText("    ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_nombre)
                        .addGap(18, 18, 18)
                        .addComponent(jl_nombreMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_curp)
                        .addGap(18, 18, 18)
                        .addComponent(jl_curpMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_claveElector)
                        .addGap(18, 18, 18)
                        .addComponent(jl_claveElectorMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_rfc)
                        .addGap(18, 18, 18)
                        .addComponent(jl_rfcMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_estudios)
                        .addGap(18, 18, 18)
                        .addComponent(jl_estudiosMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_especialidad)
                        .addGap(18, 18, 18)
                        .addComponent(jl_especialidadMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_convenioMedico)
                        .addGap(18, 18, 18)
                        .addComponent(jl_convenioMedicoMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_tipoSangre)
                        .addGap(18, 18, 18)
                        .addComponent(jl_tipoSangreMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_fechaNacimiento)
                        .addGap(18, 18, 18)
                        .addComponent(jl_fechaNacimientoMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_recomendado)
                        .addGap(18, 18, 18)
                        .addComponent(jl_recomendadoMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_domicilio)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jl_domicilio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_domicilioMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(jl_domicilio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(jl_hijos_mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_concuvina)
                        .addGap(18, 18, 18)
                        .addComponent(jl_concuvinaMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_estadoCivil)
                        .addGap(18, 18, 18)
                        .addComponent(jl_estadocivilMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jl_apodo)
                                .addGap(18, 18, 18)
                                .addComponent(jl_apodoMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_apodo)
                                    .addComponent(jl_apodoMostrar))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_estadoCivil)
                                    .addComponent(jl_estadocivilMostrar))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_concuvina)
                                    .addComponent(jl_concuvinaMostrar))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel28)
                                    .addComponent(jl_hijos_mostrar))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jl_nombre)
                                        .addComponent(jl_nombreMostrar))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jl_domicilio)
                                        .addComponent(jl_domicilioMostrar))
                                    .addGap(18, 18, 18)
                                    .addComponent(jl_domicilio2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jl_domicilio3)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jl_curp)
                                        .addComponent(jl_curpMostrar))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jl_claveElector)
                                        .addComponent(jl_claveElectorMostrar))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jl_rfc)
                                        .addComponent(jl_rfcMostrar))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jl_convenioMedico)
                                        .addComponent(jl_convenioMedicoMostrar))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jl_tipoSangre)
                                        .addComponent(jl_tipoSangreMostrar))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jl_fechaNacimiento)
                                        .addComponent(jl_fechaNacimientoMostrar))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jl_recomendado)
                                        .addComponent(jl_recomendadoMostrar))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jl_estudios)
                                        .addComponent(jl_estudiosMostrar))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jl_especialidad)
                                        .addComponent(jl_especialidadMostrar)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Datos", jPanel2);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jt_contratos.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jt_contratos.setForeground(new java.awt.Color(0, 102, 0));
        jt_contratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contrato", "Departamento", "Categoria", "Inicio", "Fin", "Tipo", "Fecha Registro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_contratos.setComponentPopupMenu(jPopupMenu2);
        jScrollPane4.setViewportView(jt_contratos);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1127, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Contratos", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jt_credenciales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Impresion", "Departamento", "Motivo Impresion", "Tipo Credencial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jt_credenciales);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1127, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Credenciales", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_abririnfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_abririnfoActionPerformed
        // TODO add your handling code here:
        
        i = jTable1.getSelectedRow();

        if(i != -1) {
                      
            barritaProgreso = new CBarraProgreso();
            barritaProgreso.setJDProgreso(prog);
            barritaProgreso.setProgreso(0);
            barritaProgreso.setTexto("Iniciando ...");
            barritaProgreso.start();
            
            SwingWorker<String, Void> worker = new SwingWorker<String, Void>() {
            
                @Override
                protected String doInBackground(){
                    
                    jTabbedPane1.setSelectedIndex(1);

                    modelo = (DefaultTableModel) jTable1.getModel();

                    trabajador.setNoFicha(modelo.getValueAt(i, 0).toString());

                    barritaProgreso.setProgreso(30);
                    barritaProgreso.setTexto("Buscando Trabajador ...");
                    
                    trabajador.getDatosTrabajador();

                    jl_nombreMostrar.setText(trabajador.getApellidoP() + " " + trabajador.getApellidoM() + " " + trabajador.getNombre());
                    jl_domicilioMostrar.setText(trabajador.domicilio.getCalle() + " #" + trabajador.domicilio.getNumero());
                    jl_domicilio2.setText("Col. " + trabajador.domicilio.getColonia());
                    jl_domicilio3.setText(trabajador.domicilio.getCiudad() + " C.P. " + trabajador.domicilio.getCodigoPostal());
                    jl_curpMostrar.setText(trabajador.getCurp());
                    jl_rfcMostrar.setText(trabajador.getRFC());
                    jl_claveElectorMostrar.setText(trabajador.getClave());

                    jl_estudiosMostrar.setText(trabajador.estudios.getEstudios());
                    jl_especialidadMostrar.setText(trabajador.estudios.getEspecialidad());
                    jl_convenioMedicoMostrar.setText(trabajador.salud.getConvenioMedico());
                    jl_tipoSangreMostrar.setText(trabajador.salud.getTipoSangre());
                    jl_fechaNacimientoMostrar.setText(trabajador.getFechaNacimiento());
                    jl_recomendadoMostrar.setText(trabajador.getRecomendacion());
                    jl_apodoMostrar.setText(trabajador.getApodo());
                    jl_estadocivilMostrar.setText(trabajador.getEstadoCivil());

                    barritaProgreso.setProgreso(60);
                    barritaProgreso.setTexto("Buscando Informacion Familiar ...");
                    
                    if(trabajador.familia.getListadoHijos(jTable2, trabajador.getNoFicha()))
                        jl_hijos_mostrar.setText("Si");
                    else
                        jl_hijos_mostrar.setText("No");

                    trabajador.getTelefonosTrabajador(trabajador.getNoFicha(), jTable3);

                    trabajador.familia.getConcuvina(trabajador.getNoFicha());

                    jl_concuvinaMostrar.setText(trabajador.familia.getEsposa());

                    barritaProgreso.setTexto("Dibujando Foto ...");

                    foto.setFoto(trabajador.getFoto());
                    foto.repaint();
                    jPanel5.repaint(); 
                      
                    barritaProgreso.setProgreso(90);
                    barritaProgreso.setTexto("Obteniendo Historial de Contratos ...");
                     trabajador.contrato.getHistorialContratos(jt_contratos, trabajador.getNoFicha());
                    
                    barritaProgreso.setProgreso(95);
                    barritaProgreso.setTexto("Obteniendo Historial de Credenciales ...");
                    cred.getHistorialCredenciales(jt_credenciales, trabajador.getNoFicha());
                    
                    return "";
                    
                }   
            
                @Override
                protected void done() {
                    barritaProgreso.setProgreso(100);
                    barritaProgreso.setTexto("Completado ...");
                    prog.setVisible(false);
                }
            };
            
            worker.execute();
            prog.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jmi_abririnfoActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        if(!jTextField1.getText().equals("")&& evt.getKeyCode()!= 10){

            if(!trabajador.buscaTrabajadorConicidencias(jTextField1.getText(), jTable1))
                JOptionPane.showMessageDialog(this, "No se encontraron resultados con su busqueda", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jmi_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_abrirActionPerformed
        // TODO add your handling code here:
        int i = jt_contratos.getSelectedRow();

        if(i != -1) {
            exp.getArchivo("Trabajador",
                    trabajador.getNoFicha(), //expediente
                    "Contratos", // Clasificacion
                    ((String)((DefaultTableModel) jt_contratos.getModel()).getValueAt(i, 0)).replaceAll("/", "-"), //Nombre del Cocumento
                    ".jpg"); // Extension del documento

        }
        
        
    }//GEN-LAST:event_jmi_abrirActionPerformed

    private void jmi_agregarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarTelefonoActionPerformed
        // TODO add your handling code here:
        if(telefonos == null)
            telefonos = new jd_telefonos(null, true);
        
        telefonos.setVisible(true);
        
        Object [] res = telefonos.getDatos();
        
        if(res != null){
            trabajador.agregarTelefonoNuevo(res[0].toString(), res[1].toString());
            trabajador.getTelefonosTrabajador(trabajador.getNoFicha(), jTable3);
        }
        
    }//GEN-LAST:event_jmi_agregarTelefonoActionPerformed

    private void jmiBorrarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBorrarTelefonoActionPerformed
        // TODO add your handling code here:
        
        i = jTable3.getSelectedRow();
        
        if(i != -1){
        
            int res = JOptionPane.showConfirmDialog(this, "Elminar Numero Telefonico?", "Confirmar Eliminacion", JOptionPane.YES_NO_OPTION);

            if(res == JOptionPane.YES_OPTION){

                modelo = (DefaultTableModel) jTable3.getModel();
                trabajador.eliminaTelefono(modelo.getValueAt(i, 0).toString());
                trabajador.getTelefonosTrabajador(trabajador.getNoFicha(), jTable3);
            }
            
        }
        else
            JOptionPane.showMessageDialog(this, "Selecciona un registro!!!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_jmiBorrarTelefonoActionPerformed

    private void jmiActualizarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiActualizarTelefonoActionPerformed
        // TODO add your handling code here:
        i = jTable3.getSelectedRow();
        
        if(i != -1){

            modelo = (DefaultTableModel) jTable3.getModel();
            
            String telNuevo = JOptionPane.showInputDialog("Actualizar Telefono",
                    modelo.getValueAt(i, 0).toString());
            
            trabajador.actualizaTelefono(modelo.getValueAt(i, 0).toString(),telNuevo);
            trabajador.getTelefonosTrabajador(trabajador.getNoFicha(), jTable3);

        }
        else
            JOptionPane.showMessageDialog(this, "Selecciona un registro!!!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jmiActualizarTelefonoActionPerformed

    private void jb_actualizarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_actualizarFotoActionPerformed
        // TODO add your handling code here:
        if(JFileChooser.APPROVE_OPTION == jfc.showOpenDialog(this)){

            barritaProgreso = new CBarraProgreso();
            barritaProgreso.setJDProgreso(prog);
            barritaProgreso.setProgreso(0);
            barritaProgreso.setTexto("Iniciando ...");
            barritaProgreso.start();
            
            SwingWorker<String, Void> worker = new SwingWorker<String, Void>() {
            
                @Override
                protected String doInBackground(){
            
                    File archOrig = jfc.getSelectedFile();
            
                    exp.setExpediente(trabajador.getNoFicha(),"Trabajador", "Fotografias", "Foto_" + new SimpleDateFormat("dd-MM-yy").format(new Date()),
                            "Fotografia Del Trabajador Con Fecha Del " + new SimpleDateFormat("dd-MM-yy").format(new Date()),
                            "Sin Ubicacion Fisica", archOrig, archOrig.getName().substring(archOrig.getName().lastIndexOf(".")));

                    foto.setFoto(archOrig);
                    foto.repaint();
                    return "";
                    
                }   
            
                @Override
                protected void done() {
                    barritaProgreso.setProgreso(100);
                    barritaProgreso.setTexto("Completado ...");
                    prog.setVisible(false);
                }
            };
            
            worker.execute();
            prog.setVisible(true);

        }
       
    }//GEN-LAST:event_jb_actualizarFotoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jb_actualizarFoto;
    private javax.swing.JLabel jl_apodo;
    private javax.swing.JLabel jl_apodoMostrar;
    private javax.swing.JLabel jl_claveElector;
    private javax.swing.JLabel jl_claveElectorMostrar;
    private javax.swing.JLabel jl_concuvina;
    private javax.swing.JLabel jl_concuvinaMostrar;
    private javax.swing.JLabel jl_convenioMedico;
    private javax.swing.JLabel jl_convenioMedicoMostrar;
    private javax.swing.JLabel jl_curp;
    private javax.swing.JLabel jl_curpMostrar;
    private javax.swing.JLabel jl_domicilio;
    private javax.swing.JLabel jl_domicilio2;
    private javax.swing.JLabel jl_domicilio3;
    private javax.swing.JLabel jl_domicilioMostrar;
    private javax.swing.JLabel jl_especialidad;
    private javax.swing.JLabel jl_especialidadMostrar;
    private javax.swing.JLabel jl_estadoCivil;
    private javax.swing.JLabel jl_estadocivilMostrar;
    private javax.swing.JLabel jl_estudios;
    private javax.swing.JLabel jl_estudiosMostrar;
    private javax.swing.JLabel jl_fechaNacimiento;
    private javax.swing.JLabel jl_fechaNacimientoMostrar;
    private javax.swing.JLabel jl_hijos_mostrar;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JLabel jl_nombreMostrar;
    private javax.swing.JLabel jl_recomendado;
    private javax.swing.JLabel jl_recomendadoMostrar;
    private javax.swing.JLabel jl_rfc;
    private javax.swing.JLabel jl_rfcMostrar;
    private javax.swing.JLabel jl_tipoSangre;
    private javax.swing.JLabel jl_tipoSangreMostrar;
    private javax.swing.JMenuItem jmiActualizarTelefono;
    private javax.swing.JMenuItem jmiBorrarTelefono;
    private javax.swing.JMenuItem jmi_abrir;
    private javax.swing.JMenuItem jmi_abririnfo;
    private javax.swing.JMenuItem jmi_agregarTelefono;
    private javax.swing.JTable jt_contratos;
    private javax.swing.JTable jt_credenciales;
    // End of variables declaration//GEN-END:variables
}
