package vista;

import java.awt.Cursor;
import java.awt.Frame;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingWorker;
import modelo.CBarraProgreso;
import modelo.CDibujaContrato;
import modelo.CExpediente;
import modelo.CTrabajador;
import modelo.CVigilaContratos;

/**
 *
 * @author hp
 */

public class jd_contratos extends javax.swing.JDialog {

    /**
     * Creates new form jd_contratos
     */
    CTrabajador trab;
    CVigilaContratos vigila;
    CDibujaContrato dibuja;
    jd_progreso prog;
    jd_nuevaCategoria cat;
    CBarraProgreso barritaProgreso;
    CExpediente exp;
    double zoom = 1;
    boolean presionado = false ;
    
    public jd_contratos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        trab = new CTrabajador();
        
        initComponents();

        trab.contrato.getListaDepartamentos(jComboBox3);
        trab.contrato.getListaCategorias(jComboBox2);
        
        dibuja = new CDibujaContrato(jPanel2);
        jPanel2.add(dibuja);
        
        if(prog == null)
            prog = new jd_progreso((Frame) getParent(), true);

        exp = new CExpediente();

        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jb_siguienteContrato = new javax.swing.JButton();
        jb_actualizarListado = new javax.swing.JButton();
        jb_eliminarContrato = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jb_guardarContrato = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta Contrato");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jPanel2MouseWheelMoved(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentResized(evt);
            }
        });

        jb_siguienteContrato.setText(">");
        jb_siguienteContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_siguienteContratoActionPerformed(evt);
            }
        });

        jb_actualizarListado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/recycle-29933_960_720.png"))); // NOI18N
        jb_actualizarListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_actualizarListadoActionPerformed(evt);
            }
        });

        jb_eliminarContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/limp.png"))); // NOI18N
        jb_eliminarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarContratoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icon-home.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_siguienteContrato)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(jb_eliminarContrato)
                .addGap(18, 18, 18)
                .addComponent(jb_actualizarListado)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_siguienteContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jb_eliminarContrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_actualizarListado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("No. Ficha:");

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("  ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Datos Contrato");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Fecha Inicio:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Fecha Fin:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Categoria:");

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(0, 153, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Departamento:");

        jComboBox3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(0, 102, 0));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Comentarios:");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 102, 0));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jb_guardarContrato.setText("Guardar");
        jb_guardarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarContratoActionPerformed(evt);
            }
        });

        jDateChooser1.setForeground(new java.awt.Color(0, 102, 0));
        jDateChooser1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jDateChooser2.setForeground(new java.awt.Color(0, 102, 0));
        jDateChooser2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Clave:");

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 108, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jb_guardarContrato))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jb_guardarContrato)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:     
        if(!jTextField1.getText().equals("")){
            
            trab.setNoFicha(jTextField1.getText());
            
            if(trab.getNombreTrabajadorBD()){
                jLabel3.setText(trab.getNombre() + " " + trab.getApellidoP() + " " + trab.getApellidoM());
            }
            else
                JOptionPane.showMessageDialog(this, "Trabajador no encontrado.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(this, "Por favor verifica los datos.", "Aviso", JOptionPane.WARNING_MESSAGE);
   
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        try{

        if(jComboBox3.getSelectedItem().equals("*Nuevo")){
            
            String res;
            res = JOptionPane.showInputDialog(this, "Introduce el nuevo Departamento", "Nuevo Tipo", JOptionPane.DEFAULT_OPTION);   
            
            if(res != null){
                
                JOptionPane.showMessageDialog(this, trab.contrato.setNuevoDepartamento(res), "Aviso", JOptionPane.INFORMATION_MESSAGE); 
                trab.contrato.getListaDepartamentos(jComboBox3);
                
            }
            else
                JOptionPane.showMessageDialog(this, "Valor Incorrecto", "Aviso", JOptionPane.WARNING_MESSAGE);

        }
        }catch(NullPointerException e){    
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
//        vigila.terminaPrograma();
        
    }//GEN-LAST:event_formWindowClosed

    private void jPanel2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jPanel2MouseWheelMoved
        // TODO add your handling code here:
         if(evt.getWheelRotation()<0)

             dibuja.acercar();
          
         else
            dibuja.Alejar();

         dibuja.repaint();
         jPanel2.repaint();
        
    }//GEN-LAST:event_jPanel2MouseWheelMoved

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        dibuja.setCoordenadasRaton(evt.getX(), evt.getY());
        dibuja.Desplazar();
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        jPanel2.setCursor(new Cursor(Cursor.MOVE_CURSOR));
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
        // TODO add your handling code here:jPanel2.setCursor(new Cursor(Cursor.MOVE_CURSOR));
        jPanel2.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanel2MouseReleased

    private void jb_siguienteContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_siguienteContratoActionPerformed
        // TODO add your handling code here:
     SwingWorker<String, Void> worker = new SwingWorker<String, Void>() {
            
                @Override
                protected String doInBackground(){

                    barritaProgreso = new CBarraProgreso();
                    barritaProgreso.setJDProgreso(prog);
                    barritaProgreso.setProgreso(0);
                    barritaProgreso.setTexto("Iniciando ...");
                    barritaProgreso.start();        

                    barritaProgreso.setProgreso(60);
                    barritaProgreso.setTexto("Obteniendo Contrato ...");

                    trab.contrato.getArchivoContrato(vigila.siguiente());
                    
                    barritaProgreso.setProgreso(90);
                    barritaProgreso.setTexto("Dibujando ...");
                    
                    dibuja.nuevo();
                    dibuja.setFoto(new File(System.getProperty("java.io.tmpdir") + File.separator + vigila.getArchivoActual()));

                    dibuja.repaint();
                    jPanel2.repaint();
                   
                    return "";
                    
                }   
            
                @Override
                protected void done() {

                    barritaProgreso.setProgreso(100);
                    barritaProgreso.setTexto("Completado ...");
                    prog.setVisible(false);
                    
                }
            };
            
            worker.execute();
            
            prog.setVisible(true);
            
    }//GEN-LAST:event_jb_siguienteContratoActionPerformed

    private void jb_actualizarListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_actualizarListadoActionPerformed
        // TODO add your handling code here:
        
        vigila.actualizarListado();
        
        if(vigila.existenArchivos()){
            
            trab.contrato.getArchivoContrato(vigila.siguiente());
            
            dibuja.setFoto(new File(System.getProperty("java.io.tmpdir") + File.separator + vigila.getArchivoActual()));
            
            dibuja.repaint();
            jPanel2.repaint();
            
            jb_siguienteContrato.setEnabled(true);
            jb_guardarContrato.setEnabled(true);
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Parece que no existen archivos de contratos disponibles",
                                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
            
            jb_siguienteContrato.setEnabled(false);
            jb_guardarContrato.setEnabled(false);
            
        }
        
    }//GEN-LAST:event_jb_actualizarListadoActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        try{

            if(jComboBox2.getSelectedItem().equals("*Nuevo")){
                
                cat = new jd_nuevaCategoria((Frame) getParent(), true);
                
                cat.setVisible(true);
                
                JOptionPane.showMessageDialog(this, trab.contrato.setNuevaCategoria(cat.getValores())
                        , "Aviso", JOptionPane.INFORMATION_MESSAGE);
                
                trab.contrato.getListaCategorias(jComboBox2);
        
            }
        }catch(NullPointerException e){    
        }
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jb_guardarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarContratoActionPerformed
        // TODO add your handling code here:
        if(!jComboBox2.getSelectedItem().equals("Selecciona") && !jComboBox3.getSelectedItem().equals("Selecciona") && !jLabel3.getText().isEmpty()){
            if(!jTextField1.getText().isEmpty() && !jTextField2.getText().isEmpty() && !jTextArea1.getText().isEmpty()){
                if(!jDateChooser1.getDate().equals(new Date()) && !jDateChooser2.getDate().equals(new Date())){
                    
                    SwingWorker<String, Void> worker = new SwingWorker<String, Void>() {

                        @Override
                        protected String doInBackground(){
                            
                            String tipoContrato;
                            
                            barritaProgreso = new CBarraProgreso();
                            barritaProgreso.setJDProgreso(prog);
                            barritaProgreso.setProgreso(0);
                            barritaProgreso.setTexto("Iniciando ...");
                            barritaProgreso.start();        

                            barritaProgreso.setProgreso(30);
                            barritaProgreso.setTexto("Registrando Contrato ...");
                            
                            tipoContrato = jTextField2.getText();
                            
                            if(tipoContrato.startsWith("AS-"))
                                tipoContrato = "Ascenso";
                            else if(tipoContrato.startsWith("PCS-"))
                                tipoContrato = "Comision";
                            else if(tipoContrato.startsWith("CS-"))
                                tipoContrato = "Eventual";
                            else if(tipoContrato.startsWith("VS-"))
                                tipoContrato = "Vacaciones";
                            else if(tipoContrato.startsWith("ND-"))
                                tipoContrato = "Nombramiento";
                            else
                                tipoContrato = "Ninguno";
                                
                            
                            if(tipoContrato.equals("Nombramiento")){
                                trab.contrato.setFechaFin(null);                                    
                            }
                            else
                                trab.contrato.setFechaFin(jDateChooser2.getDate());

                            trab.contrato.setTipo(tipoContrato);

                            trab.contrato.setTrabajador(jTextField1.getText());
                            trab.contrato.setNoContrato(jTextField2.getText());
                            trab.contrato.setFechaInicio(jDateChooser1.getDate());
                            trab.contrato.setDepartamento(jComboBox3.getSelectedItem().toString());
                            trab.contrato.setCategoria(jComboBox2.getSelectedItem().toString());

                            if(!tipoContrato.equals("Ninguno")){
                                
                                String res = trab.contrato.setRegistraContrato();

                                if(res.equals("Contrato Registrado Exitosamente.")){

                                    barritaProgreso.setProgreso(60);
                                    barritaProgreso.setTexto("Actualizando Expediente...");

                                    res = exp.setExpediente(trab.getNoFicha(), "Trabajador" , "Contratos", jTextField2.getText().replaceAll("/", "-"),
                                    "Contrato del Trabajador " + trab.getNoFicha() + " con fecha del " + new Date().toString()
                                    + " Que dicta lo siguiente: " + jTextArea1.getText(),"Sin Ubicacion Fisica",
                                    new File(System.getProperty("java.io.tmpdir") + vigila.getArchivoActual()),
                                    vigila.getArchivoActual().substring(vigila.getArchivoActual().lastIndexOf(".")));

                                    if(res.equals("Expediente Registrado.")){

                                        barritaProgreso.setProgreso(80);
                                        barritaProgreso.setTexto("Obteniendo el siguiente contrato ...");

                                        vigila.deleteFile();

                                        vigila.actualizarListado();

                                        if(vigila.existenArchivos()){

                                            trab.contrato.getArchivoContrato(vigila.getArchivoActual());
                                            dibuja.nuevo();
                                            dibuja.setFoto(new File(System.getProperty("java.io.tmpdir") + File.separator + vigila.getArchivoActual()));

                                            dibuja.repaint();
                                            jPanel2.repaint();

                                            barritaProgreso.setProgreso(100);
                                            barritaProgreso.setTexto("Completado.");
                                            prog.setVisible(false);
                                            jb_guardarContrato.setEnabled(true);

                                        }
                                        else{                                       
                                            prog.setVisible(false);                                        
                                            JOptionPane.showMessageDialog(null, "Parece que no existen archivos de contratos disponibles",
                                                "Error", JOptionPane.ERROR_MESSAGE);  

                                            dibuja.setFoto(null);
                                            dibuja.repaint();
                                            jPanel2.repaint();
                                            jb_guardarContrato.setEnabled(false);

                                        }                

                                        JOptionPane.showMessageDialog(null, "Contrato Registrado Exitosamente",
                                                "Error", JOptionPane.INFORMATION_MESSAGE); 

                                        jTextField1.setText("");
                                        jTextField2.setText("");
                                        jComboBox2.setSelectedItem("Selecciona");
                                        jComboBox3.setSelectedItem("Selecciona");
                                        jLabel3.setText("");
                                        jTextArea1.setText("");
                                        ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText("");
                                        ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).setText("");

                                    }
                                    else{                                    
                                        prog.setVisible(false);
                                        JOptionPane.showMessageDialog(null, "Expediente NO Actualizado UUID Duplicado!",
                                            "Error", JOptionPane.ERROR_MESSAGE);
                                    } 
                                }
                                else{
                                    prog.setVisible(false);
                                    JOptionPane.showMessageDialog(null, "Contrado Dulicado!",
                                            "Error", JOptionPane.ERROR_MESSAGE);
                                }
                            }
                            else{
                                prog.setVisible(false);
                                JOptionPane.showMessageDialog (null, "Tipo de contrato no reconocido", "Virifica los datos", JOptionPane.WARNING_MESSAGE);
                            }
                            return "";

                        }   

                        @Override
                        protected void done() {
                            prog.setVisible(false);
                        }
                    };

                    worker.execute();
                    prog.setVisible(true);
                    
                }
                else
                    JOptionPane.showMessageDialog(this, "Por favor verifica los datos, si el contrato es Nombramiento Definitivo, selecciona una fecha de Fin Aleatoria", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(this, "Por favor verifica los datos", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(this, "Por favor verifica los datos", "Aviso", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_jb_guardarContratoActionPerformed

    private void jb_eliminarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarContratoActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "¿Eliminar archivo?", "Confirmar", JOptionPane.YES_NO_OPTION);
        
        if(res == JOptionPane.YES_OPTION){

            SwingWorker<String, Void> worker = new SwingWorker<String, Void>() {
            
                @Override
                protected String doInBackground(){
                    
                    vigila.deleteFile();
                    vigila.actualizarListado();
                    
                    barritaProgreso = new CBarraProgreso();
                    barritaProgreso.setJDProgreso(prog);
                    barritaProgreso.setProgreso(0);
                    barritaProgreso.setTexto("Iniciando ...");
                    barritaProgreso.start();        

                    barritaProgreso.setProgreso(60);
                    barritaProgreso.setTexto("Obteniendo Contrato ...");

                    trab.contrato.getArchivoContrato(vigila.siguiente());
                    
                    barritaProgreso.setProgreso(90);
                    barritaProgreso.setTexto("Dibujando ...");
                    
                    dibuja.nuevo();
                    dibuja.setFoto(new File(System.getProperty("java.io.tmpdir") + File.separator + vigila.getArchivoActual()));

                    dibuja.repaint();
                    jPanel2.repaint();
                   
                    return "";
                    
                }   
            
                @Override
                protected void done() {

                    barritaProgreso.setProgreso(100);
                    barritaProgreso.setTexto("Completado ...");
                    prog.setVisible(false);
                    
                }
            };
            
            worker.execute();
            
            prog.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_jb_eliminarContratoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dibuja.nuevo();
        dibuja.setFoto(new File(System.getProperty("java.io.tmpdir") + File.separator + vigila.getArchivoActual()));

        dibuja.repaint();
        jPanel2.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentResized
        // TODO add your handling code here:
        if(dibuja != null){
            dibuja.setSize(jPanel2.getSize());
            dibuja.repaint();
            jPanel2.repaint();
        }
        
    }//GEN-LAST:event_jPanel2ComponentResized

    public void inicarHiloDeContratos() throws IOException{
        
        SwingWorker<String, Void> worker = new SwingWorker<String, Void>() {
            
                @Override
                protected String doInBackground(){

                    barritaProgreso = new CBarraProgreso();
                    barritaProgreso.setJDProgreso(prog);
                    barritaProgreso.setProgreso(0);
                    barritaProgreso.setTexto("Iniciando ...");
                    barritaProgreso.start();        

                    barritaProgreso.setProgreso(40);
                    barritaProgreso.setTexto("Obteniendo Lista de Contratos ...");

                    vigila = new CVigilaContratos();
                    vigila.actualizarListado();

                    barritaProgreso.setProgreso(60);
                    barritaProgreso.setTexto("Obteniendo Contrato ...");

                    dibuja.setSize(jPanel2.getSize());
                    dibuja.repaint();
                    
                    if(vigila.existenArchivos()){

                        if(trab.contrato.getArchivoContrato(vigila.siguiente())){
                            
                            dibuja.setFoto(new File(System.getProperty("java.io.tmpdir") + File.separator + vigila.getArchivoActual()));

                            dibuja.repaint();
                            jPanel2.repaint();
                            
                            jb_siguienteContrato.setEnabled(true);
                            jb_guardarContrato.setEnabled(true);
                            
                        }
                        else{
                            
                            barritaProgreso.setProgreso(100);
                            
                            prog.setVisible(false);
                            
                            JOptionPane.showMessageDialog(null, "Parace existir un problema con el servicio FTP, contacte al administrador",
                                    "Error", JOptionPane.ERROR_MESSAGE);
                        }

                    }
                    else{
                        
                        barritaProgreso.setProgreso(100);
                            
                        prog.setVisible(false);
                        
                        
                        JOptionPane.showMessageDialog(null, "Parece que no existen archivos de contratos disponibles",
                                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        
                        jb_siguienteContrato.setEnabled(false);
                        jb_guardarContrato.setEnabled(false);
                        
                    }

                    return "";
                }   
            
                @Override
                protected void done() {

                    barritaProgreso.setProgreso(100);
                    barritaProgreso.setTexto("Completado ...");
                    prog.setVisible(false);
                    
                }
            };
            
            worker.execute();
            
            prog.setVisible(true);
            
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jb_actualizarListado;
    private javax.swing.JButton jb_eliminarContrato;
    private javax.swing.JButton jb_guardarContrato;
    private javax.swing.JButton jb_siguienteContrato;
    // End of variables declaration//GEN-END:variables
}
