/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import modelo.CTrabajador;
import modelo.CftpClient;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class jd_cambioDeFicha extends javax.swing.JDialog {

    /**
     * Creates new form jd_cambioDeFicha
     */
    CTrabajador trab;
    CftpClient ftp;
    boolean continuar;
    
    public jd_cambioDeFicha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        trab = new CTrabajador();
        ftp = new CftpClient();
        setLocationRelativeTo(parent);
        
        jtf_fichaNueva.setEditable(false);
        jta_descripcionProblema.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_fichaAnterior = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_descripcionProblema = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jtf_fichaNueva = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cambio de Ficha");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("No. Ficha:");

        jtf_fichaAnterior.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtf_fichaAnterior.setForeground(new java.awt.Color(255, 0, 0));
        jtf_fichaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_fichaAnteriorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("     ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Nueva Ficha:");

        jta_descripcionProblema.setColumns(20);
        jta_descripcionProblema.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jta_descripcionProblema.setForeground(new java.awt.Color(0, 102, 0));
        jta_descripcionProblema.setLineWrap(true);
        jta_descripcionProblema.setRows(5);
        jScrollPane1.setViewportView(jta_descripcionProblema);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Descripcion del Problema:");

        jtf_fichaNueva.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtf_fichaNueva.setForeground(new java.awt.Color(0, 102, 0));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Save-icon.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtf_fichaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtf_fichaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1))
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_fichaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_fichaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_fichaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_fichaAnteriorActionPerformed
        // TODO add your handling code here:
        if(!jtf_fichaAnterior.getText().equals("")){
            
            trab.setNoFicha(jtf_fichaAnterior.getText());
            
            if(trab.getNombreTrabajadorBD()){
                
                jLabel3.setText(trab.getNombre() + " " + trab.getApellidoP() + " " + trab.getApellidoM());
               
                jtf_fichaNueva.setEditable(true);
                jta_descripcionProblema.setEditable(true);
                continuar = true;
                
            }
            else{
                
                JOptionPane.showMessageDialog(this, "Trabajador no encontrado.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
               
                jtf_fichaNueva.setEditable(false);
                jta_descripcionProblema.setEditable(false);
            
            }

        }
        
    }//GEN-LAST:event_jtf_fichaAnteriorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!jta_descripcionProblema.getText().equals("") && !jtf_fichaAnterior.getText().equals("") && !jtf_fichaNueva.getText().equals("")  && continuar){
   
            if( ftp.cambioFicha(jtf_fichaAnterior.getText(), jtf_fichaNueva.getText())){
                
               Object []  res =  trab.setNuevaFicha(jtf_fichaAnterior.getText(), jtf_fichaNueva.getText(), jta_descripcionProblema.getText());

               JOptionPane.showMessageDialog(this, res[0], "Aviso", JOptionPane.INFORMATION_MESSAGE);
               
               JOptionPane.showMessageDialog(this, res[1], "Aviso", JOptionPane.INFORMATION_MESSAGE);
               
                jtf_fichaNueva.setEditable(false);
                jta_descripcionProblema.setEditable(false);
                continuar = false;
                
                jtf_fichaAnterior.setText("");
                jtf_fichaNueva.setText("");
                jta_descripcionProblema.setText("");
                jLabel3.setText("       ");
               
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Verifica que los datos sean correctos", "Aviso", JOptionPane.WARNING_MESSAGE);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jta_descripcionProblema;
    private javax.swing.JTextField jtf_fichaAnterior;
    private javax.swing.JTextField jtf_fichaNueva;
    // End of variables declaration//GEN-END:variables
}
