package vista;

import java.awt.Frame;
import javax.swing.JOptionPane;
import modelo.CCredencial;

/**
 *
 * @author Tadeo
 */

public class jd_credenciales extends javax.swing.JDialog {

    CCredencial credencial;
    jd_credencialesPendientes credenPen = null;
    
    public jd_credenciales(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        buttonGroup1.add(jrb_trabajador);
        buttonGroup1.add(jrb_directiva);
        
        credencial = new CCredencial();
        credencial.setLienzo(jPanel5);
        credencial.getMotivosImpresion(jcb_motivoImpresion);
        jPanel5.add(credencial.getLienzo());
        jrb_trabajador.setSelected(true);
        setLocationRelativeTo(parent);
        credencial.getTrabajador().contrato.getListaDepartamentos(jcb_departamentos);
        credencial.getDatosDirectiva().getCargosDirectiva(jcb_directiva);
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jcb_departamentos = new javax.swing.JComboBox();
        jcb_directiva = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jl_noFicha = new javax.swing.JLabel();
        jtf_noFicha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jcb_motivoImpresion = new javax.swing.JComboBox();
        jl_tipoCredencial = new javax.swing.JLabel();
        jrb_trabajador = new javax.swing.JRadioButton();
        jrb_directiva = new javax.swing.JRadioButton();
        jb_buscar = new javax.swing.JButton();
        jb_imprimir = new javax.swing.JButton();
        jb_guardaCredencial = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jcb_departamentos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_departamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_departamentosActionPerformed(evt);
            }
        });

        jcb_directiva.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_directiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_directivaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jl_noFicha.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_noFicha.setText("No. Ficha:");

        jtf_noFicha.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtf_noFicha.setForeground(new java.awt.Color(255, 0, 0));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Motivo Impresion:");

        jcb_motivoImpresion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jcb_motivoImpresion.setForeground(new java.awt.Color(0, 153, 0));
        jcb_motivoImpresion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "*Nuevo" }));
        jcb_motivoImpresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_motivoImpresionActionPerformed(evt);
            }
        });

        jl_tipoCredencial.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jl_tipoCredencial.setText("Tipo Credencial:");

        jrb_trabajador.setBackground(new java.awt.Color(255, 255, 255));
        jrb_trabajador.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jrb_trabajador.setText("Trabajador");

        jrb_directiva.setBackground(new java.awt.Color(255, 255, 255));
        jrb_directiva.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jrb_directiva.setText("Directiva");

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa.png"))); // NOI18N
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });

        jb_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono_imprime.jpg"))); // NOI18N
        jb_imprimir.setEnabled(false);
        jb_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_imprimirActionPerformed(evt);
            }
        });

        jb_guardaCredencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Save-icon.png"))); // NOI18N
        jb_guardaCredencial.setEnabled(false);
        jb_guardaCredencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardaCredencialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jb_guardaCredencial)
                        .addGap(18, 18, 18)
                        .addComponent(jb_imprimir)
                        .addGap(18, 18, 18)
                        .addComponent(jb_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jl_noFicha)
                            .addGap(18, 18, 18)
                            .addComponent(jtf_noFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jl_tipoCredencial)
                            .addGap(18, 18, 18)
                            .addComponent(jrb_trabajador)
                            .addGap(18, 18, 18)
                            .addComponent(jrb_directiva))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jcb_motivoImpresion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_noFicha)
                    .addComponent(jtf_noFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_tipoCredencial)
                    .addComponent(jrb_trabajador)
                    .addComponent(jrb_directiva))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcb_motivoImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_imprimir)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jb_buscar)
                        .addComponent(jb_guardaCredencial)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Logo SUTSHA Azul finalSF_3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu2.setText("Operaciones");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuItem2.setText("Credenciales Pendientes ...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
        // TODO add your handling code here:
        if(!jcb_motivoImpresion.getSelectedItem().equals("Selecciona")){
        
            if(jrb_directiva.isSelected()){
                
                String res = credencial.getDatosCredencial(jtf_noFicha.getText(), "Directiva");
                
                JOptionPane.showMessageDialog(this, res, "Aviso", JOptionPane.INFORMATION_MESSAGE);
                
                if(!res.equals("Trabajador no encontrado.")){

                        do{
                            JOptionPane.showMessageDialog(this, jcb_directiva, "Seleciona el cargo en la Directiva", JOptionPane.QUESTION_MESSAGE);
                        }while("Selecciona".equals(jcb_directiva.getSelectedItem().toString()));
                        
                        credencial.getDatosDirectiva().setCargo(jcb_directiva.getSelectedItem().toString());
                        credencial.getDatosDirectiva().setTrabajador(credencial.getTrabajador());
                        credencial.dibujaCredencialDirectiva();
                        jPanel5.repaint();                        
                        jb_imprimir.setEnabled(true);
                        jb_guardaCredencial.setEnabled(true);

                }
                
            }
            else{
                
                String res = credencial.getDatosCredencial(jtf_noFicha.getText(), "Trabajador");
                
                JOptionPane.showMessageDialog(this, res, "Aviso", JOptionPane.INFORMATION_MESSAGE);
                
                if(!res.equals("Trabajador no encontrado.")){
                
                
                    if(credencial.getTrabajador().contrato.getDepartamento() == null){

                        JOptionPane.showMessageDialog(this, "Se han encontrado datos del trabajador, pero ningun contrato registrado de el. \n Por favor, selecciona manualmente el departamento", "Aviso",
                        JOptionPane.INFORMATION_MESSAGE);
                        
                        do{
                            JOptionPane.showMessageDialog(this, jcb_departamentos, "Seleciona el departamento", JOptionPane.QUESTION_MESSAGE);
                        }while("Selecciona".equals(jcb_departamentos.getSelectedItem().toString()));
                        
                        credencial.getTrabajador().contrato.setDepartamento(jcb_departamentos.getSelectedItem().toString());    
                        credencial.dibujaCredencialTrabajador();
                        jPanel5.repaint();
                        jb_imprimir.setEnabled(true);
                        jb_guardaCredencial.setEnabled(true);
   
                    }
                    else{
                        credencial.dibujaCredencialTrabajador();
                        jPanel5.repaint();
                        jb_imprimir.setEnabled(true);
                        jb_guardaCredencial.setEnabled(true);
                    }
                }
                
            }
            
        }
        
    }//GEN-LAST:event_jb_buscarActionPerformed

    private void jcb_motivoImpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_motivoImpresionActionPerformed
        // TODO add your handling code here:
        try{

        if(jcb_motivoImpresion.getSelectedItem().equals("*Nuevo")){
            
            String res;
            res = JOptionPane.showInputDialog(this, "Introduce el nuevo motivo de impresion:", "Nuevo Motivo", JOptionPane.DEFAULT_OPTION);   
            
            if(res != null){
                
                JOptionPane.showMessageDialog(this, credencial.setNuevoMotivo(res), "Aviso", JOptionPane.INFORMATION_MESSAGE); 
                 credencial.getMotivosImpresion(jcb_motivoImpresion);
                
            }
            else
                JOptionPane.showMessageDialog(this, "Valor Incorrecto", "Aviso", JOptionPane.WARNING_MESSAGE);

        }
        }catch(NullPointerException e){    
        }
 
    }//GEN-LAST:event_jcb_motivoImpresionActionPerformed

    private void jb_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_imprimirActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, "Imprimir Credencial", "Aviso", JOptionPane.YES_NO_OPTION)){

            if(jrb_directiva.isSelected())
                credencial.generaCredencialArchivoDirectiva();
            else
                credencial.generaCredencialArchivoTrabajador();
            
            if(credencial.prepararImpresion()){
                
                if(jrb_directiva.isSelected())
                    credencial.registraCredencial(jcb_motivoImpresion.getSelectedItem().toString(),"Directiva");
                else
                    credencial.registraCredencial(jcb_motivoImpresion.getSelectedItem().toString(),"Trabajador");
                
                JOptionPane.showMessageDialog(this, "Credencial Impresa", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                
                limpiar();
                
            }
            else{
                JOptionPane.showMessageDialog(this, "Parece existir un problema con la impresora, contacte al administrador", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }

        }

    }//GEN-LAST:event_jb_imprimirActionPerformed

    private void jcb_departamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_departamentosActionPerformed
        // TODO add your handling code here:
        try{

            if(jcb_departamentos.getSelectedItem().equals("*Nuevo")){

                String res;
                res = JOptionPane.showInputDialog(this, "Introduce el nuevo departamento:", "Nuevo Tipo", JOptionPane.DEFAULT_OPTION);   

                if(res != null){

                    JOptionPane.showMessageDialog(this, credencial.getTrabajador().contrato.setNuevoDepartamento(res), "Aviso", JOptionPane.INFORMATION_MESSAGE); 
                     credencial.getTrabajador().contrato.getListaDepartamentos(jcb_departamentos);

                }
                else
                    JOptionPane.showMessageDialog(this, "Valor Incorrecto", "Aviso", JOptionPane.WARNING_MESSAGE);

        }
        }catch(NullPointerException e){    
        }
  
    }//GEN-LAST:event_jcb_departamentosActionPerformed

    private void jb_guardaCredencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardaCredencialActionPerformed
        // TODO add your handling code here:
        if(jrb_directiva.isSelected())
            JOptionPane.showMessageDialog(this, "No se Pueden Guardar Credenciales de la Directiva", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        else
            credencial.registraCredencialPendiente(jcb_motivoImpresion.getSelectedItem().toString(), "Trabajador");
        
        JOptionPane.showMessageDialog(this, "Credencial registrada como pendiente.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        limpiar();
    }//GEN-LAST:event_jb_guardaCredencialActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if(credenPen == null){
            credenPen = new jd_credencialesPendientes((Frame) getParent(), true);
            credenPen.setVisible(true);
        }
        else
            credenPen.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jcb_directivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_directivaActionPerformed
        // TODO add your handling code here:
        try{

            if(jcb_directiva.getSelectedItem().equals("*Nuevo")){

                String res;
                res = JOptionPane.showInputDialog(this, "Introduce el nuevo cargo en la directiva:", "Nuevo Cargo", JOptionPane.DEFAULT_OPTION);   

                if(res != null){

                    JOptionPane.showMessageDialog(this, credencial.getDatosDirectiva().setNuevoCargoDirectiva(res), "Aviso", JOptionPane.INFORMATION_MESSAGE); 
                    credencial.getDatosDirectiva().getCargosDirectiva(jcb_directiva);

                }
                else
                    JOptionPane.showMessageDialog(this, "Valor Incorrecto", "Aviso", JOptionPane.WARNING_MESSAGE);

        }
        }catch(NullPointerException e){    
        }
    }//GEN-LAST:event_jcb_directivaActionPerformed

    private void limpiar(){
        
        jcb_departamentos.setSelectedItem("Selecciona");
        jcb_motivoImpresion.setSelectedItem("Selecciona");
        jtf_noFicha.setText("");
        
        credencial.getLienzo().queCredencialDibujo("Limpiar");
        credencial.getLienzo().repaint();
        jPanel5.repaint();
  
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_guardaCredencial;
    private javax.swing.JButton jb_imprimir;
    private javax.swing.JComboBox jcb_departamentos;
    private javax.swing.JComboBox jcb_directiva;
    private javax.swing.JComboBox jcb_motivoImpresion;
    private javax.swing.JLabel jl_noFicha;
    private javax.swing.JLabel jl_tipoCredencial;
    private javax.swing.JRadioButton jrb_directiva;
    private javax.swing.JRadioButton jrb_trabajador;
    private javax.swing.JTextField jtf_noFicha;
    // End of variables declaration//GEN-END:variables
}
