package vista;

import javax.swing.ButtonGroup;
import modelo.CTrabajador;

/**
 *
 * @author Laptop-Sony
 */

public class jd_vistaContratos extends javax.swing.JDialog {

    /**
     * Creates new form jd_vistaContratos
     */
    CTrabajador trab;
    
    public jd_vistaContratos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        buttonGroup1.add(jrb_departamento);
        buttonGroup1.add(jrb_categoria);
        buttonGroup1.add(jrb_verTodos);
        buttonGroup1.add(jrb_trabajador);

        trab = new CTrabajador();
        
        setLocationRelativeTo(parent);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcb_departamentos = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_datosContratos = new javax.swing.JTable();
        jrb_departamento = new javax.swing.JRadioButton();
        jrb_categoria = new javax.swing.JRadioButton();
        jcb_categorias = new javax.swing.JComboBox();
        jrb_verTodos = new javax.swing.JRadioButton();
        jrb_trabajador = new javax.swing.JRadioButton();
        jtf_trabajador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion Contratos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Contratos Sutsha");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Filtrar por:");

        jcb_departamentos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_departamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_departamentosActionPerformed(evt);
            }
        });

        jt_datosContratos.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jt_datosContratos.setForeground(new java.awt.Color(0, 102, 0));
        jt_datosContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Ficha", "Nombre", "Departamento", "Categoria", "Salario", "Inicio", "Fin", "Contrato"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_datosContratos);

        jrb_departamento.setBackground(new java.awt.Color(255, 255, 255));
        jrb_departamento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jrb_departamento.setForeground(new java.awt.Color(0, 0, 153));
        jrb_departamento.setText("Departamento");

        jrb_categoria.setBackground(new java.awt.Color(255, 255, 255));
        jrb_categoria.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jrb_categoria.setForeground(new java.awt.Color(0, 0, 153));
        jrb_categoria.setText("Categoria");

        jcb_categorias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_categoriasActionPerformed(evt);
            }
        });

        jrb_verTodos.setBackground(new java.awt.Color(255, 255, 255));
        jrb_verTodos.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jrb_verTodos.setForeground(new java.awt.Color(0, 0, 153));
        jrb_verTodos.setText("Todos");
        jrb_verTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_verTodosActionPerformed(evt);
            }
        });

        jrb_trabajador.setBackground(new java.awt.Color(255, 255, 255));
        jrb_trabajador.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jrb_trabajador.setForeground(new java.awt.Color(0, 0, 102));
        jrb_trabajador.setText("Trabajador");
        jrb_trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_trabajadorActionPerformed(evt);
            }
        });

        jtf_trabajador.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtf_trabajador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_trabajadorKeyTyped(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Logo SUTSHA Azul finalSF_3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jrb_trabajador))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrb_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcb_departamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtf_trabajador))
                                .addGap(18, 18, 18)
                                .addComponent(jrb_categoria)
                                .addGap(18, 18, 18)
                                .addComponent(jcb_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jrb_verTodos)
                                .addGap(0, 115, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcb_departamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrb_departamento)
                            .addComponent(jrb_categoria)
                            .addComponent(jcb_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrb_verTodos))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrb_trabajador)
                            .addComponent(jtf_trabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        trab.contrato.getListaDepartamentos(jcb_departamentos);
        trab.contrato.getListaCategorias(jcb_categorias);
        trab.contrato.getContratos(jt_datosContratos);
        jrb_verTodos.setSelected(true);
    }//GEN-LAST:event_formWindowOpened

    private void jcb_departamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_departamentosActionPerformed
        // TODO add your handling code here:
        try{
            trab.contrato.buscaSobreDepartamento(jt_datosContratos, jcb_departamentos.getSelectedItem().toString());
            jrb_departamento.setSelected(true);
            jtf_trabajador.setText("");
        }catch(NullPointerException x){
            
        }
    }//GEN-LAST:event_jcb_departamentosActionPerformed

    private void jcb_categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_categoriasActionPerformed
        // TODO add your handling code here:
        try{
            trab.contrato.buscaSobreCategoria(jt_datosContratos, jcb_categorias.getSelectedItem().toString());
            jrb_categoria.setSelected(true);
            jtf_trabajador.setText("");
        }catch(NullPointerException x){
            
        }
    }//GEN-LAST:event_jcb_categoriasActionPerformed

    private void jrb_verTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_verTodosActionPerformed
        // TODO add your handling code here:
        jcb_categorias.setSelectedItem("Selecciona");
        jcb_departamentos.setSelectedItem("Selecciona");
        jtf_trabajador.setText("");
        trab.contrato.getContratos(jt_datosContratos);
        jrb_verTodos.setSelected(true);
        jrb_verTodos.requestFocus();
    }//GEN-LAST:event_jrb_verTodosActionPerformed

    private void jtf_trabajadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_trabajadorKeyTyped
        // TODO add your handling code here:
        trab.contrato.buscaSobreTrabajador(jt_datosContratos, jtf_trabajador.getText());
        jrb_trabajador.setSelected(true);
    }//GEN-LAST:event_jtf_trabajadorKeyTyped

    private void jrb_trabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_trabajadorActionPerformed
        // TODO add your handling code here:
        jtf_trabajador.requestFocus();
    }//GEN-LAST:event_jrb_trabajadorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcb_categorias;
    private javax.swing.JComboBox jcb_departamentos;
    private javax.swing.JRadioButton jrb_categoria;
    private javax.swing.JRadioButton jrb_departamento;
    private javax.swing.JRadioButton jrb_trabajador;
    private javax.swing.JRadioButton jrb_verTodos;
    private javax.swing.JTable jt_datosContratos;
    private javax.swing.JTextField jtf_trabajador;
    // End of variables declaration//GEN-END:variables
}
